const resources = {
  areas: { id: "recno", tenantScoped: true, tag: "Areas", screenNames: ["area", "areas"], requiredOnCreate: ["name", "cityid"], listRelations: { cityid: { relation: "cities", field: "name", output: "cityname" } } },
  branches: { id: "branchid", tenantScoped: true, tag: "Branches", screenNames: ["branch", "branches"], requiredOnCreate: ["name"] },
  cities: { id: "recno", tenantScoped: true, tag: "Cities", screenNames: ["city", "cities"], requiredOnCreate: ["name", "countryid"], listRelations: { countryid: { relation: "countries", field: "name", output: "countryname" } } },
  countries: { id: "recno", tenantScoped: true, tag: "Countries", screenNames: ["country", "countries"], requiredOnCreate: ["name"] },
  customers: { id: "customerid", tenantScoped: true, branchScoped: true, tag: "Customers", screenNames: ["customer", "customers"], requiredOnCreate: ["name"], listRelations: { country: { relation: "countries", field: "name", output: "countryname" }, city: { relation: "cities", field: "name", output: "cityname" }, area: { relation: "areas", field: "name", output: "areaname" }, branchid: { relation: "branches", field: "name", output: "branchname" } } },
  jobcategories: { id: "categoryid", tenantScoped: true, branchScoped: true, tag: "Job Categories", screenNames: ["jobcategory", "job category", "jobcategories", "job categories"], requiredOnCreate: ["name", "groupid"], listRelations: { groupid: { relation: "jobgroups", field: "name", output: "groupname" }, branchid: { relation: "branches", field: "name", output: "branchname" } } },
  jobgroups: { id: "groupid", tenantScoped: true, branchScoped: true, tag: "Job Groups", screenNames: ["jobgroup", "job group", "jobgroups", "job groups"], requiredOnCreate: ["name"], listRelations: { branchid: { relation: "branches", field: "name", output: "branchname" } } },
  jobstauses: { id: "recno", tenantScoped: true, tag: "Job Statuses", screenNames: ["jobstatus", "job status", "jobstauses", "job statuses"], requiredOnCreate: ["title"] },
  jobsubcategories: { id: "subcategoryid", tenantScoped: true, branchScoped: true, tag: "Job Subcategories", screenNames: ["jobsubcategory", "job subcategory", "jobsubcategories", "job subcategories"], requiredOnCreate: ["name", "categoryid"], listRelations: { categoryid: { relation: "jobcategories", field: "name", output: "categoryname" }, branchid: { relation: "branches", field: "name", output: "branchname" } } },
  organizations: { id: "tenantid", tenantScoped: true, noCreate: true, tag: "Organizations", screenNames: ["organization", "organizations"] },
  policies: { id: "recno", tenantScoped: true, tag: "Policies", screenNames: ["policy", "policies"], requiredOnCreate: ["description"] },
  products: { id: "productid", tenantScoped: true, branchScoped: true, tag: "Products", screenNames: ["product", "products"], requiredOnCreate: ["name"], listRelations: { branchid: { relation: "branches", field: "name", output: "branchname" } } },
  screens: { id: "screenid", backendOnly: true },
  userorganizations: { id: "recno", tenantScoped: true, branchScoped: true, tag: "User Organizations", screenNames: ["userorganization", "user organization", "userorganizations", "user organizations"], requiredOnCreate: ["userid"], listRelations: { userid: { relation: "users_userorganizations_useridTousers", field: "name", output: "username" }, branchid: { relation: "branches", field: "name", output: "branchname" } } },
  userpolicies: { id: "recno", tenantScoped: true, branchScoped: true, tag: "User Policies", screenNames: ["userpolicy", "user policy", "userpolicies", "user policies"], requiredOnCreate: ["userid", "policyid"], listRelations: { userid: { relation: "users_userpolicies_useridTousers", field: "name", output: "username" }, policyid: { relation: "policies", field: "description", output: "policyname" }, branchid: { relation: "branches", field: "name", output: "branchname" } } },
  userrights: { id: "recno", tenantScoped: true, branchScoped: true, tag: "User Rights", screenNames: ["userright", "user right", "userrights", "user rights"], requiredOnCreate: ["screenid", "policyid"], listRelations: { screenid: { relation: "screens", field: "screenname", output: "screenname" }, policyid: { relation: "policies", field: "description", output: "policyname" }, branchid: { relation: "branches", field: "name", output: "branchname" } } },
  users: { id: "userid", noCreate: true, tag: "Users", screenNames: ["user", "users"] },
  userssignuptokenlogs: { id: "recno", tenantScoped: true, noCreate: true, backendOnly: true }
};

module.exports = resources;
